// 12 dados fakes para contas a pagar
export const contasPagarFakes = [
  {
    id: 1,
    codigo: "CP-0001",
    descricao: "Compra de Materiais Odontológicos",
    fornecedor: "Dental Prime",
    categoria: "Materiais" as const,
    valor_original: 1200.50,
    valor_pago: 0,
    valor_pendente: 1200.50,
    data_vencimento: "2025-12-05",
    status: "Pendente" as const,
    prioridade: "Alta" as const,
    forma_pagamento: "Boleto",
    observacoes: "Entrega prevista para 20/12/2025",
    created_at: "2025-12-01"
  },
  {
    id: 2,
    codigo: "CP-0002",
    descricao: "Aluguel da Clínica",
    fornecedor: "Imobiliária Central",
    categoria: "Aluguel" as const,
    valor_original: 3500.00,
    valor_pago: 3500.00,
    valor_pendente: 0,
    data_vencimento: "2025-12-01",
    data_pagamento: "2025-12-01",
    status: "Pago" as const,
    prioridade: "Crítica" as const,
    forma_pagamento: "Transferência",
    observacoes: "Pago em dia",
    created_at: "2025-11-01"
  },
  {
    id: 3,
    codigo: "CP-0003",
    descricao: "Conta de Energia",
    fornecedor: "Energia SP",
    categoria: "Energia" as const,
    valor_original: 890.00,
    valor_pago: 0,
    valor_pendente: 890.00,
    data_vencimento: "2025-12-10",
    status: "Pendente" as const,
    prioridade: "Média" as const,
    forma_pagamento: "Pix",
    observacoes: "Vencimento próximo",
    created_at: "2025-11-20"
  },
  {
    id: 4,
    codigo: "CP-0004",
    descricao: "Serviço de Internet",
    fornecedor: "NetFast",
    categoria: "Internet" as const,
    valor_original: 199.90,
    valor_pago: 199.90,
    valor_pendente: 0,
    data_vencimento: "2025-11-30",
    data_pagamento: "2025-11-30",
    status: "Pago" as const,
    prioridade: "Baixa" as const,
    forma_pagamento: "Cartão de Débito",
    observacoes: "",
    created_at: "2025-11-10"
  },
  {
    id: 5,
    codigo: "CP-0005",
    descricao: "Impostos Municipais",
    fornecedor: "Prefeitura",
    categoria: "Impostos" as const,
    valor_original: 450.00,
    valor_pago: 0,
    valor_pendente: 450.00,
    data_vencimento: "2025-12-20",
    status: "Pendente" as const,
    prioridade: "Alta" as const,
    forma_pagamento: "Boleto",
    observacoes: "",
    created_at: "2025-11-15"
  },
  {
    id: 6,
    codigo: "CP-0006",
    descricao: "Compra de Medicamentos",
    fornecedor: "Farmácia Odonto",
    categoria: "Medicamentos" as const,
    valor_original: 320.00,
    valor_pago: 320.00,
    valor_pendente: 0,
    data_vencimento: "2025-11-28",
    data_pagamento: "2025-11-28",
    status: "Pago" as const,
    prioridade: "Média" as const,
    forma_pagamento: "Dinheiro",
    observacoes: "",
    created_at: "2025-11-05"
  },
  {
    id: 7,
    codigo: "CP-0007",
    descricao: "Serviço de Limpeza",
    fornecedor: "Limpeza Express",
    categoria: "Serviços" as const,
    valor_original: 250.00,
    valor_pago: 0,
    valor_pendente: 250.00,
    data_vencimento: "2025-12-03",
    status: "Pendente" as const,
    prioridade: "Baixa" as const,
    forma_pagamento: "Pix",
    observacoes: "Limpeza mensal",
    created_at: "2025-11-18"
  },
  {
    id: 8,
    codigo: "CP-0008",
    descricao: "Telefone Fixo",
    fornecedor: "Vivo",
    categoria: "Telefone" as const,
    valor_original: 99.90,
    valor_pago: 99.90,
    valor_pendente: 0,
    data_vencimento: "2025-11-29",
    data_pagamento: "2025-11-29",
    status: "Pago" as const,
    prioridade: "Baixa" as const,
    forma_pagamento: "Cartão de Crédito",
    observacoes: "",
    created_at: "2025-11-09"
  },
  {
    id: 9,
    codigo: "CP-0009",
    descricao: "Compra de Equipamentos",
    fornecedor: "Odonto Equip",
    categoria: "Equipamentos" as const,
    valor_original: 5000.00,
    valor_pago: 0,
    valor_pendente: 5000.00,
    data_vencimento: "2025-12-15",
    status: "Pendente" as const,
    prioridade: "Crítica" as const,
    forma_pagamento: "Cheque",
    observacoes: "Pagamento após entrega",
    created_at: "2025-11-22"
  },
  {
    id: 10,
    codigo: "CP-0010",
    descricao: "Serviço de Consultoria",
    fornecedor: "Consultoria Odonto",
    categoria: "Serviços" as const,
    valor_original: 800.00,
    valor_pago: 0,
    valor_pendente: 800.00,
    data_vencimento: "2025-12-08",
    status: "Pendente" as const,
    prioridade: "Média" as const,
    forma_pagamento: "Transferência",
    observacoes: "Consultoria mensal",
    created_at: "2025-11-12"
  },
  {
    id: 11,
    codigo: "CP-0011",
    descricao: "Compra de Cadeiras",
    fornecedor: "Odonto Móveis",
    categoria: "Equipamentos" as const,
    valor_original: 1500.00,
    valor_pago: 0,
    valor_pendente: 1500.00,
    data_vencimento: "2025-12-18",
    status: "Pendente" as const,
    prioridade: "Alta" as const,
    forma_pagamento: "Boleto",
    observacoes: "Entrega prevista para 20/12/2025",
    created_at: "2025-12-01"
  },
  {
    id: 12,
    codigo: "CP-0012",
    descricao: "Serviço de Pintura",
    fornecedor: "Pintura Express",
    categoria: "Serviços" as const,
    valor_original: 800.00,
    valor_pago: 0,
    valor_pendente: 800.00,
    data_vencimento: "2025-12-22",
    status: "Pendente" as const,
    prioridade: "Média" as const,
    forma_pagamento: "Pix",
    observacoes: "Pintura anual",
    created_at: "2025-12-01"
  }
];
